INSERT INTO seats ("row", "column", "location_id", "is_booked")
VALUES
    (1, 'a', 1, false),
    (1, 'b', 1, false),
    (1, 'c', 1, false),
    (1, 'd', 1, false),
    (1, 'e', 1, false),
    (2, 'a', 1, false),
    (2, 'b', 1, false),
    (2, 'c', 1, false),
    (2, 'd', 1, false),
    (2, 'e', 1, false),
    (3, 'a', 1, false),
    (3, 'b', 1, false),
    (3, 'c', 1, false),
    (3, 'd', 1, false),
    (3, 'e', 1, false),
    (4, 'a', 1, false),
    (4, 'b', 1, false),
    (4, 'c', 1, false),
    (4, 'd', 1, false),
    (4, 'e', 1, false),
    (5, 'a', 1, false),
    (5, 'b', 1, false),
    (5, 'c', 1, false),
    (5, 'd', 1, false),
    (5, 'e', 1, false);
